version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - books
      - loans1
      - loans2

  books:
    build: ./books
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/booksdb
    depends_on:
      - mongo
    restart: always

  loans1:
    build: ./loans
    ports:
      - "5002:5002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/loansdb
      - BOOKS_SERVICE_URL=http://books:5001
    depends_on:
      - mongo
    restart: always

  loans2:
    build: ./loans
    ports:
      - "5003:5002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/loansdb
      - BOOKS_SERVICE_URL=http://books:5001
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"